// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kin_stellar_stats.Database;

namespace kin_stellar_stats.Migrations
{
    [DbContext(typeof(ManagementContext))]
    [Migration("20180725031349_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("kin_stellar_stats.Database.Models.Pagination", b =>
                {
                    b.Property<string>("CursorType")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PagingToken");

                    b.HasKey("CursorType");

                    b.HasIndex("CursorType")
                        .IsUnique();

                    b.ToTable("Paginations");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.FlattenedBalance", b =>
                {
                    b.Property<string>("KinAccountId");

                    b.Property<string>("AssetType");

                    b.Property<string>("AssetCode");

                    b.Property<string>("BalanceString");

                    b.Property<string>("Limit");

                    b.HasKey("KinAccountId", "AssetType");

                    b.ToTable("FlattenedBalance");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.FlattenedOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("EffectType");

                    b.Property<string>("Memo");

                    b.Property<string>("PagingToken");

                    b.Property<string>("SourceAccount");

                    b.Property<string>("TransactionHash");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("FlattenedOperation");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FlattenedOperation");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.KinAccount", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountCreditedCount");

                    b.Property<int>("AccountCreditedVolume");

                    b.Property<int>("AccountDebitedCount");

                    b.Property<int>("AccountDebitedVolume");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<DateTimeOffset>("LastActive");

                    b.Property<string>("Memo");

                    b.HasKey("Id");

                    b.ToTable("KinAccounts");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.FlattenCreateAccountOperation", b =>
                {
                    b.HasBaseType("kin_stellar_stats.Database.StellarObjectWrappers.FlattenedOperation");

                    b.Property<string>("Account");

                    b.Property<string>("Funder");

                    b.Property<string>("StartingBalance");

                    b.ToTable("FlattenCreateAccountOperation");

                    b.HasDiscriminator().HasValue("FlattenCreateAccountOperation");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.FlattenPaymentOperation", b =>
                {
                    b.HasBaseType("kin_stellar_stats.Database.StellarObjectWrappers.FlattenedOperation");

                    b.Property<string>("Amount");

                    b.Property<string>("AssetCode");

                    b.Property<string>("AssetIssuer");

                    b.Property<string>("AssetType");

                    b.Property<string>("From");

                    b.Property<string>("To");

                    b.ToTable("FlattenPaymentOperation");

                    b.HasDiscriminator().HasValue("FlattenPaymentOperation");
                });

            modelBuilder.Entity("kin_stellar_stats.Database.StellarObjectWrappers.FlattenedBalance", b =>
                {
                    b.HasOne("kin_stellar_stats.Database.StellarObjectWrappers.KinAccount")
                        .WithMany("FlattenedBalance")
                        .HasForeignKey("KinAccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
